### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by pjebs** [edekhayser/TiltingScrollView#1]
Is it possible to make this into an extension instead of a subclass so I can use it with a different subclass of UIScrollView?

**Comment by edekhayser** [comment]
It would be very difficult, at best. There are several properties that I needed to add to this class (which you can see in the source file), which cannot be added to an extension without Associated Classes (which may be one possible solution to this problem).

Is it possible that you can change the subclass to inherit from TiltingScrollView instead? That way, you could get all the benefits of this class while still inheriting from UIScrollView.

**Comment by pjebs** [comment]
I can't change the subclass. That's the problem. I was going to mention Associated objects but noticed you already knew about it

**Comment by edekhayser** [comment]
I'll look into it when I get a chance.

**Comment by edekhayser** [comment]
@pjebs Check out this latest commit. I haven't had much time to test it, but I believe that it is working as it is supposed to as an extension.

**Comment by pjebs** [comment]
Awesome work. You just increased its utility 20 fold.
